// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8knywajSVwBQ3WnTi2KdVlubgZzpbkRE',
    appId: '1:221801074126:web:f94548b8ea51e7e2076f9f',
    messagingSenderId: '221801074126',
    projectId: 'nodes-apps',
    authDomain: 'nodes-apps.firebaseapp.com',
    storageBucket: 'nodes-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKYlfpHhl5QzxBfSaQ8ITv9copP04LIQ',
    appId: '1:221801074126:android:52090a0986e86635076f9f',
    messagingSenderId: '221801074126',
    projectId: 'nodes-apps',
    storageBucket: 'nodes-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwnTeBpR6TSffM0jm3fW6hN2PlCPJ3xA8',
    appId: '1:221801074126:ios:8c4ad89503893889076f9f',
    messagingSenderId: '221801074126',
    projectId: 'nodes-apps',
    storageBucket: 'nodes-apps.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwnTeBpR6TSffM0jm3fW6hN2PlCPJ3xA8',
    appId: '1:221801074126:ios:8c4ad89503893889076f9f',
    messagingSenderId: '221801074126',
    projectId: 'nodes-apps',
    storageBucket: 'nodes-apps.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8knywajSVwBQ3WnTi2KdVlubgZzpbkRE',
    appId: '1:221801074126:web:a8e082879751e933076f9f',
    messagingSenderId: '221801074126',
    projectId: 'nodes-apps',
    authDomain: 'nodes-apps.firebaseapp.com',
    storageBucket: 'nodes-apps.firebasestorage.app',
  );
}
